### ISSUE TITLE
 Create state error = ReferenceError: initialise is not defined

### ISSUE THREAD

**Issue by NN93** [DrozmotiX/ioBroker.wled#133]
**After add the Wled in Iobroker I get a lot of error message always the same message**

wled.0 | 2021-02-17 22:10:34.287 | error | (1833) Create state error = ReferenceError: initialise is not defined
-- | -- | -- | --
wled.0 | 2021-02-17 22:10:34.280 | error | (1833) Create state error = ReferenceError: initialise is not defined
wled.0 | 2021-02-17 22:10:33.939 | error | (1833) Create state error = ReferenceError: initialise is not defined
wled.0 | 2021-02-17 22:10:33.934 | error | (1833) Create state error = ReferenceError: initialise is not defined
wled.0 | 2021-02-17 22:10:03.582 | error | (1833) Create state error = ReferenceError: initialise is not defined
wled.0 | 2021-02-17 22:10:03.579 | error | (1833) Create state error = ReferenceError: initialise is not defined
wled.0 | 2021-02-17 22:10:03.408 | error | (1833) Create state error = ReferenceError: initialise is not defined
wled.0 | 2021-02-17 22:10:03.406 | error | (1833) Create state error = ReferenceError: initialise is not defined
wled.0 | 2021-02-17 22:09:33.063 | error | (1833) Create state error = ReferenceError: initialise is not defined

**Comment by DutchmanNL** [comment]
Do not install from git 😉

**Comment by NN93** [comment]
Hello Dutchman

I have a lot of error messages in the log, which keeps repeating. I install the adapter vom iobroker.

[cid:image001.png@01D714C7.333C0D60]

[cid:image002.png@01D714C7.333C0D60]

Kind regards
N. Nelson

Von: Dutchman <notifications@github.com>
Gesendet: Dienstag, 9. März 2021 06:52
An: iobroker-community-adapters/ioBroker.wled <ioBroker.wled@noreply.github.com>
Cc: NN93 <neshanthan-nelson@hotmail.com>; State change <state_change@noreply.github.com>
Betreff: Re: [iobroker-community-adapters/ioBroker.wled] Create state error = ReferenceError: initialise is not defined (#133)


Do not install from git 😉

**Comment by DutchmanNL** [comment]
will be solved by https://github.com/iobroker-community-adapters/ioBroker.wled/issues/145

**Comment by DutchmanNL** [comment]
solved 0.5.7
