### ISSUE TITLE
WLED verliert die Verbindung

### ISSUE THREAD

**Issue by guergen1** [DrozmotiX/ioBroker.wled#153]
Zu unterschiedlichen Zeiten verliert WLED die Verbindung zum NodeCU. Ein Reset oder Neustart des Adapters hilt nicht. 
Ich muss den Adapter löschen und neu installieren

`

2021-03-17 17:39:11.857  - error:  wled.0 (9571) Unhandled promise rejection. This error originated either  by throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().
2021-03-17 17:39:11.858  - error: wled.0 (9571) unhandled promise rejection: Cannot read property 'error' of undefined
2021-03-17 17:39:11.860  - error: wled.0 (9571) TypeError: Cannot read property 'error' of undefined
at Wled.onUnload (/opt/iobroker/node_modules/iobroker.wled/main.js:97:13)
at Wled.emit (events.js:314:20)
at process.stop (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8620:22)
at Object.onceWrapper (events.js:421:26)
at process.emit (events.js:314:20)
at process.exit (internal/process/per_thread.js:168:15)
at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:352:25)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-03-17 17:39:11.860  - error: wled.0 (9571) Cannot read property 'error' of undefined

`

**Versions:**  
 - Adapter version: 0.5.6
 - JS-Controller version: 3.2.16
 - Node version: 12.21.0
 - Operating system: Debian 10.2.0

**Comment by DutchmanNL** [comment]
Sure you did install from admin and not git ?
Basic communication will be changed within the next month by handling enhancement 

https://github.com/iobroker-community-adapters/ioBroker.wled/issues/145

**Comment by DutchmanNL** [comment]
> I installed it from admin!
> I´m on latest:
> ![grafik](https://user-images.githubusercontent.com/34395245/111511498-1934f800-874f-11eb-9f12-dca0e3850f19.png)

Clear thanks, still I will not solve that specific one as currently the adapter is using the json api and polling. The whole Logic will change to Web service which is much mir stable and should also solve this behaviour ☺️

**Comment by Optic00** [comment]
> > I am still having the same problem with the stable and from github 0.5.9
> 
> Which wled version?

 wled version on both: 0.12.0

deleting the adapter and reinstalling will fix the issue for a day or two than stops working again. Both wled controllers show up as connected, both wled controllers can be controlled via webbrowser on the same network.

**Comment by DutchmanNL** [comment]
please try 0.6.0-1

**Comment by Optic00** [comment]
installed 0.6.0-1 - unable to manually add wled controllers now (they are on another subnet for IoT devices). 

- Did a clean install of the adapter, not an upgrade. 
- Tried to upload old config, no wled controllers show up. 
- Restarting Adapter doesn't help.

**Comment by DutchmanNL** [comment]
Thanks will Look Into it

**Comment by DutchmanNL** [comment]
> installed 0.6.0-1 - unable to manually add wled controllers now (they are on another subnet for IoT devices).

should be fixed in v0.6.0-2

**Comment by Optic00** [comment]
> should be fixed in v0.6.0-2

thank you! that is fixed. Now objects don't get properly populated. No On/off Object etc.

<img width="1248" alt="Bildschirmfoto 2021-08-28 um 22 42 05" src="https://user-images.githubusercontent.com/20187253/131230560-81133e48-587e-4fcd-9cfa-682b58b69148.png">

**Comment by DutchmanNL** [comment]
> thank you! that is fixed. Now objects don't get properly populated. No On/off Object etc.

please try 0.6.0-3

**Comment by Optic00** [comment]
> please try 0.6.0-3

after removing and reinstalling it works! :-) let me test this a few days and ill report back.
thank you again!

**Comment by DutchmanNL** [comment]
> > please try 0.6.0-3
> 
> after removing and reinstalling it works! :-) let me test this a few days and ill report back.
> thank you again!

Great good news ! 😁 yes let’s keep the issue open for a couple of days we will see what @guergen1 will report back 😉

**Comment by guergen1** [comment]
Ich denke dass es jetzt so läuft. Keine Abbrüche oder Unterbrechungen mehr. 
Auch nach mehrmaligen Ein und Ausschalten der LED-Streifen keine Verbindungsabbrüche
Danke!

**Comment by DutchmanNL** [comment]
> Ich denke dass es jetzt so läuft. Keine Abbrüche oder Unterbrechungen mehr.
> Auch nach mehrmaligen Ein und Ausschalten der LED-Streifen keine Verbindungsabbrüche
> Danke!

super, na dan mach ich hier mal zu :)
Wen es weiter keine Fehler gibt werde ich naechse Woche nach stable releasen zusammen mit der WLED 0.13-b2 release

**Comment by Optic00** [comment]
Muss mich leider nochmal melden. Die Verbindung zu einem der beiden wled controller funktioniert leider nicht mehr. Per WLAN weiterhin alles erreichbar, IP hat sich nicht geändert. 

Der zweite Controller (Garagentor) läuft weiterhin. Status on/off ändert sich auch nicht wenn ich direkt das wled modul über den Browser schalte.

Kann ich weitere Informationen/Debugging bereitstellen?

**Comment by DutchmanNL** [comment]
> Kann ich weitere Informationen/Debugging bereitstellen?

Was kommt im log und welche Version hat der Controller (und dein wled Adapter )?

**Comment by Optic00** [comment]
0.6.0-3 vom Adapter und 0.12.0 (build 2104020) vom wled controller
im Log vom iobroker sehe ich so leider nichts

**Comment by DutchmanNL** [comment]
> 0.6.0-3 vom Adapter und 0.12.0 (build 2104020) vom wled controller
> im Log vom iobroker sehe ich so leider nichts

da muss was im log kommen beim starten des adapter, sonst mal bitte loglevel auf debug stellen

<img width="1244" alt="Schermafbeelding 2021-09-01 om 09 04 02" src="https://user-images.githubusercontent.com/7318445/131627011-462131df-82c7-4eea-9ba1-1d1a64f3d3f3.png">

**Comment by Optic00** [comment]
auf 0.6 Release geupdated (eben gesehen), Adapter neu gestartet, Log schaut alles gut aus, 
WLED tuts jetzt wieder. Beobachte weiter.

**Comment by DutchmanNL** [comment]
> auf 0.6 Release geupdated (eben gesehen), Adapter neu gestartet, Log schaut alles gut aus,
> WLED tuts jetzt wieder. Beobachte weiter.

zwischen 0.6.0-3 und 0.6.0 hat sich nichts geaendert im code zur wled Steuerung nur die art und weise wie sentry angesprochen wird

**Comment by Optic00** [comment]
wieder dieselbe Problematik wie oben beschrieben. Adapter löschen und neu installieren hilft ein paar Tage, dann funktioniert es wieder nicht.

**Comment by DutchmanNL** [comment]
> wieder dieselbe Problematik wie oben beschrieben. Adapter löschen und neu installieren hilft ein paar Tage, dann funktioniert es wieder nicht.

Adapter löschen/neu installieren ist nicht sinnvoll in der Situation ioBroker neu starten reicht

werde mein wled project die Tage mal ausstauben und schauen ob ich es reproduziert bekomme

**Comment by DutchmanNL** [comment]
@Optic00 welche WLED version ? im forum haben wir bemerkt das die 0.12b Probleme und 0.12 Probleme machen kan mit dem socket

**Comment by Optic00** [comment]
@DutchmanNL 0.12 build 2104020
nach dem Neustart vom IOBroker funktioniert wieder alles seit 3-4 Tagen. Ist dann nicht eher das Problem woanders als bei der WLED Firmware? 

Auch das nach dem IOBroker Neustart oder Neuinstallation vom Plugin es erst wieder läuft ist ja seltsam.
Macht es ggf. Sinn hier optional den Adapter 1x am Tag neu zu starten? 

Ich schaue auch mal ob es hier am Neustart von der Firewall liegen könnte (wenn es Updates gibt usw.), die IoT Geräte liegen hier in einem eigenen Netz (anderes Netz als der IOBroker)

**Comment by DutchmanNL** [comment]
> nach dem Neustart vom IOBroker funktioniert wieder alles seit 3-4 Tagen. Ist dann nicht eher das Problem woanders als bei der WLED Firmware?

wuerde man vermuten, aber siehe forum post man kan es reproduzieren... upgrade bitte mal auf WLED 0.13 bin gespannt oben das Problem dan immer noch bleibt

**Comment by Optic00** [comment]
hab mal update gemacht auf 0.13 und beobachte es. Danke!
