### ISSUE TITLE
Get Names from WLED Modules

### ISSUE THREAD

**Issue by ToTXR4Y** [DrozmotiX/ioBroker.wled#181]
Moin,

in der Adminoberfläche werden die WLED Module ja mit der MAC-Adresse dargestellt. Hier wäre es noch schön, wenn das Device bereits einen Hostnamen zugewiesen bekommen hat (über die WLED Oberfläche), das dieser auch in der Admin bzw. vielleicht sogar in der Objekt-Liste auftaucht und dort zugewiesen wird.

Wenn das Device nachträglich geändert wird, dann sollte er diese Änderung mitnehmen :-)

**Comment by DutchmanNL** [comment]
this is already implemented, adapter needs a reboot to avoid to much write actions to device objects wen adopting the name
Will check in the rework to have this handled also during runtime
