### ISSUE TITLE
Changing lor value doesn't work

### ISSUE THREAD

**Issue by n0valis** [DrozmotiX/ioBroker.wled#191]
is this a bug or normal and just not possible?
If it is possible, what could be a reason that it doesn't work?
No problem to change other settings.

**Comment by Ceel84** [comment]
i have the same Problem

**Comment by DutchmanNL** [comment]
https://github.com/DrozmotiX/ioBroker.wled/issues/252

fixed in latest git version, will include in release 0.5.8
