### ISSUE TITLE
Adapter throws errors in log

### ISSUE THREAD

**Issue by Haui74** [DrozmotiX/ioBroker.wled#209]
(22797) Create state error = ReferenceError: initialise is not defined

**Comment by foxriver76** [comment]
Would also be fixed with https://github.com/DrozmotiX/ioBroker.wled/pull/190 because there's a variable which has a typo in it one or two times.

**Comment by DutchmanNL** [comment]
will fix bij next release with socket implementation, as usual... don't install from git this error is only on git version not official release....

**Comment by DutchmanNL** [comment]
fixed release v0.5.7
