### ISSUE TITLE
Wrong typ nach Umstellung auf js-controller 3.x.x

### ISSUE THREAD

**Issue by JBSullivan** [DrozmotiX/ioBroker.wled#215]
wled Version 0.5.6
Admin 5.1.4
js-controller 3.3.11

Ich habe heute erstmals wled installiert und folgenden Fehler bekommen, welcher im Rahmen des Admin/js-controller Updates auch schon andere Adapter betroffen hat.

Es wundert mich nur, das hier noch kein Issue dazu eröffnet wurde - oder habe ich es übersehen? Die "Problematik" ist ja schon mit der ersten Admin 5.x.x Version aufgetreten.

`

wled.0 | 2021-05-28 21:18:27.564 | info | (4400) State value to set for "wled.0.8caab5d20cfe.seg.0.col.2" has to be one of type "string", "number", "boolean" but received type "object"
-- | -- | -- | --
wled.0 | 2021-05-28 21:18:27.553 | info | (4400) State value to set for "wled.0.8caab5d20cfe.seg.0.col.1" has to be one of type "string", "number", "boolean" but received type "object"
wled.0 | 2021-05-28 21:18:27.543 | info | (4400) State value to set for "wled.0.8caab5d20cfe.seg.0.col.0" has to be one of type "string", "number", "boolean" but received type "object"
wled.0 | 2021-05-28 21:18:27.424 | info | (4400) State value to set for "wled.0.8caab5d20cfe._info.mac" has to be type "number" but received type "string"
wled.0 | 2021-05-28 21:18:27.296 | info | (4400) State value to set for "wled.0.8caab5d20cfe._info.leds.pin" has to be one of type "string", "number", "boolean" but received type "object"
wled.0 | 2021-05-28 21:17:57.176 | info | (4400) State value to set for "wled.0.8caab5d20cfe.seg.0.col.2" has to be one of type "string", "number", "boolean" but received type "object"
wled.0 | 2021-05-28 21:17:57.172 | info | (4400) State value to set for "wled.0.8caab5d20cfe.seg.0.col.1" has to be one of type "string", "number", "boolean" but received type "object"
wled.0 | 2021-05-28 21:17:57.166 | info | (4400) State value to set for "wled.0.8caab5d20cfe.seg.0.col.0" has to be one of type "string", "number", "boolean" but received type "object"
wled.0 | 2021-05-28 21:17:57.089 | info | (4400) State value to set for "wled.0.8caab5d20cfe._info.mac" has to be type "number" but received type "string"
wled.0 | 2021-05-28 21:17:57.024 | info | (4400) State value to set for "wled.0.8caab5d20cfe._info.leds.pin" has to be one of type "string", "number", "boolean" but received type "object"
wled.0 | 2021-05-28 21:17:26.938 | info | (4400) State value to set for "wled.0.8caab5d20cfe.seg.0.col.2" has to be one of type "string", "number", "boolean" but received type "object"
wled.0 | 2021-05-28 21:17:26.934 | info | (4400) State value to set for "wled.0.8caab5d20cfe.seg.0.col.1" has to be one of type "string", "number", "boolean" but received type "object"
wled.0 | 2021-05-28 21:17:26.930 | info | (4400) State value to set for "wled.0.8caab5d20cfe.seg.0.col.0" has to be one of type "string", "number", "boolean" but received type "object"
wled.0 | 2021-05-28 21:17:26.836 | info | (4400) State value to set for "wled.0.8caab5d20cfe._info.mac" has to be type "number" but received type "string"
wled.0 | 2021-05-28 21:17:26.771 | info | (4400) State value to set for "wled.0.8caab5d20cfe._info.leds.pin" has to be one of type "string", "number", "boolean" but received type "object"
wled.0 | 2021-05-28 21:16:56.686 | info | (4400) State value to set for "wled.0.8caab5d20cfe.seg.0.col.2" has to be one of type "string", "number", "boolean" but received type "object"
wled.0 | 2021-05-28 21:16:56.678 | info | (4400) State value to set for "wled.0.8caab5d20cfe.seg.0.col.1" has to be one of type "string", "number", "boolean" but received type "object"
wled.0 | 2021-05-28 21:16:56.671 | info | (4400) State value to set for "wled.0.8caab5d20cfe.seg.0.col.0" has to be one of type "string", "number", "boolean" but received type "object"
wled.0 | 2021-05-28 21:16:56.578 | info | (4400) State value to set for "wled.0.8caab5d20cfe._info.mac" has to be type "number" but received type "string"
wled.0 | 2021-05-28 21:16:56.485 | info | (4400) State value to set for "wled.0.8caab5d20cfe._info.leds.pin" has to be one of type "string", "number", "boolean" but received type "object"
wled.0 | 2021-05-28 21:16:26.388 | info | (4400) State value to set for "wled.0.8caab5d20cfe.seg.0.col.2" has to be one of type "string", "number", "boolean" but received type "object"
wled.0 | 2021-05-28 21:16:26.384 | info | (4400) State value to set for "wled.0.8caab5d20cfe.seg.0.col.1" has to be one of type "string", "number", "boolean" but received type "object"
wled.0 | 2021-05-28 21:16:26.379 | info | (4400) State value to set for "wled.0.8caab5d20cfe.seg.0.col.0" has to be one of type "string", "number", "boolean" but received type "object"
wled.0 | 2021-05-28 21:16:26.286 | info | (4400) State value to set for "wled.0.8caab5d20cfe._info.mac" has to be type "number" but received type "string"
wled.0 | 2021-05-28 21:16:26.207 | info | (4400) State value to set for "wled.0.8caab5d20cfe._info.leds.pin" has to be one of type "string", "number", "boolean" but received type "object"

`

**Comment by KLVN** [comment]
Duplicate https://github.com/DrozmotiX/ioBroker.wled/issues/189

**Comment by DutchmanNL** [comment]
fixed release v0.5.7
