### ISSUE TITLE
Adapter stops working without sign

### ISSUE THREAD

**Issue by Chris87-ux** [DrozmotiX/ioBroker.wled#224]
Adapter showed "green" as well all WLED devices were shown as connected, but some of them multiple times.
![image](https://user-images.githubusercontent.com/55442459/121636923-ea49cc00-ca88-11eb-8d98-fb19e69aeaa2.png)

After restarting the addapter following errors were shown:
![image](https://user-images.githubusercontent.com/55442459/121636888-dc944680-ca88-11eb-839b-593c8049b328.png)

No Datapoint will be updated either from WLED device side (if i change something on the web UI of the WLED device) or from the datapoint to the WLED device.

Restart don't help.

After a complete reinstallation everything is working again, but only found on WLED device automatically the other once i had to add manually.

Information to my system Running on a MW on Proxmox: 
![image](https://user-images.githubusercontent.com/55442459/121637672-0d28b000-ca8a-11eb-89f2-bd4be594003a.png)

**Comment by DutchmanNL** [comment]
should be fixed in 0.5.7
