### ISSUE TITLE
info.u.PIR has no existing object

### ISSUE THREAD

**Issue by Rushmed** [DrozmotiX/ioBroker.wled#254]
Hello,

pls find my issue here:
https://github.com/Aircoookie/WLED/issues/2122

Thanksd in further.

**Comment by DutchmanNL** [comment]
fixed release v0.5.7

**Comment by Rushmed** [comment]
Still got:
`
<html>
<body>


wled.0 | 5357 | 2021-08-11 00:12:54.892 | warn | Used invalid characters: wled.0.e8db849b8ebe._info.u.PIR <i class="icons">&#xe325;</i> changed to wled.0.e8db849b8ebe._info.u.PIR _i class=_icons_&#xe325_/i_
-- | -- | -- | -- | --



</body>
</html>`

**Comment by DutchmanNL** [comment]
please test 0.5.8 :)

**Comment by DutchmanNL** [comment]
for now I just removed this value completely as the PIR attribute has a kind of html format where o can create a state for

https://github.com/DrozmotiX/ioBroker.wled/commit/42a948b6864b681e01a867056e1d29b808614c2b#diff-58417e0f781b6656949d37258c8b9052ed266e2eb7a5163cad7b0863e6b2916aR712

**Comment by Rushmed** [comment]
Ok, the DP and the error message are gone.
