### ISSUE TITLE
Not Working after Device Reboot

### ISSUE THREAD

**Issue by AlexKusnezov** [DrozmotiX/ioBroker.wled#271]
**Describe the bug**  
After updating to the new version 0.6.3 after rebooting a WLED device, you're not able to control it in the iobroker anymore. 
Also it's not updating. After I restart the adapter it is working until WELD devices gets rebooted.

**To Reproduce**  
1. Go to WLED Devices' interface
2. Click on 'Info'
3. Click on 'Reboot WLED'
4. Click on 'Confirm'
3. Wait till it's rebooted
4. Try to control it in the iobroker

**Expected behavior**  
Shold work after wled reboot without restrtig the adapter

**Versions:**  
 - Adapter version: 0.6.3
 - JS-Controller version: 3.3.15
 - Node version: <node-version> v12.22.6
 - Operating system: Raspbian OD Buster

**Comment by DutchmanNL** [comment]
cannot reproduce, reconnection will take the amount of seconds provided in reconnection time did you wait long enough ?

**Comment by AlexKusnezov** [comment]
@DutchmanNL thnaks, problem seems to be resolved after I restarted iobroker itself

**Comment by DutchmanNL** [comment]
> @DutchmanNL thnaks, problem seems to be resolved after I restarted iobroker itself

hmm interesting, sounds like a hanging time in the backend will close here as I see no relation with the adapter :)
