### ISSUE TITLE
Update schlägt fehl. 

### ISSUE THREAD

**Issue by Lollo79** [DrozmotiX/ioBroker.wled#272]
`$ iobroker upgrade wled@0.6.1
Update wled from @0.6.0 to @0.6.1
NPM version: 6.14.14
npm install iobroker.wled@0.6.1 --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! code ETARGET
npm ERR! notarget No matching version found for iobroker.wled@0.6.1.
npm ERR! notarget In most cases you or one of your dependencies are requestingnpm ERR! notarget a package version that doesn't exist.
npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2021-09-09T17_22_18_213Z-debug.log
upload [6] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/words.js words.js application/javascript
upload [5] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/wled_large.png wled_large.png image/png
upload [4] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/wled.png wled.png image/png
upload [3] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/style.css style.css text/css
upload [2] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/index_m.html index_m.html text/html
upload [1] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/button.png button.png image/png
upload [0] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/admin.d.ts admin.d.ts video/mp2t
Adapter "wled" updated
Process exited with code 0`

**Comment by DutchmanNL** [comment]
Please update your source, 0.6.3 is in stable 0.6.1 & 0.6.2 not
