### ISSUE TITLE
No connection to Wled controller

### ISSUE THREAD

**Issue by FreunderNacht** [DrozmotiX/ioBroker.wled#275]
Recently, I can no longer get a connection to my WLED controls.

I get the following error message in the log:

`

wled.0 | 2021-09-13 18:43:15.333 | error | Cannot read property 'error' of undefined
-- | -- | -- | --
wled.0 | 2021-09-13 18:43:15.333 | error | TypeError: Cannot read property 'error' of undefined at Wled.onUnload (/opt/iobroker/node_modules/iobroker.wled/main.js:130:13) at Wled.emit (events.js:314:20) at process.stop (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8747:22) at Object.onceWrapper (events.js:421:26) at process.emit (events.js:314:20) at process.exit (internal/process/per_thread.js:168:15) at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:352:25) at processTicksAndRejections (internal/process/task_queues.js:97:5)
wled.0 | 2021-09-13 18:43:15.331 | error | unhandled promise rejection: Cannot read property 'error' of undefined
wled.0 | 2021-09-13 18:43:15.331 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
wled.0 | 2021-09-13 18:43:14.817 | warn | Terminated (ADAPTER_ALREADY_RUNNING): Without reason

`

I have restarted the adapter several times without success.

In the adapter settings, my controllers are shown as offline, but I can access them with the browser.
Everything can also be controlled there.

![Screenshot_20210913-193623](https://user-images.githubusercontent.com/69077006/133130663-eb744d5f-2339-4a83-8548-f60a6c7af239.jpg)

What could it be?

Thanks

FreundderNacht

**Comment by DutchmanNL** [comment]
Which Version this doe Not look like 0.6.3?

**Comment by DutchmanNL** [comment]
Cam you set the Adapter to denug and Send the log ?

**Comment by FreunderNacht** [comment]
I have now set it to debug, there is a few more data::

![WLED Adapter](https://user-images.githubusercontent.com/69077006/133145000-077015a5-62c5-4a4b-8bde-f253033a4ee4.jpg)

`
<html>
<body>


host.io-broker | 2021-09-13 21:28:34.098 | info | instance system.adapter.wled.0 started with pid 19010
-- | -- | -- | --
host.io-broker | 2021-09-13 21:28:32.036 | info | stopInstance system.adapter.wled.0 killing pid 18999
host.io-broker | 2021-09-13 21:28:31.032 | info | stopInstance system.adapter.wled.0 send kill signal
host.io-broker | 2021-09-13 21:28:31.023 | info | stopInstance system.adapter.wled.0 (force=false, process=true)
host.io-broker | 2021-09-13 21:26:52.560 | info | instance system.adapter.wled.0 started with pid 18999
host.io-broker | 2021-09-13 21:26:50.499 | info | stopInstance system.adapter.wled.0 killing pid 18988
host.io-broker | 2021-09-13 21:26:49.497 | info | stopInstance system.adapter.wled.0 send kill signal
host.io-broker | 2021-09-13 21:26:49.492 | info | stopInstance system.adapter.wled.0 (force=false, process=true)
host.io-broker | 2021-09-13 21:26:32.538 | info | instance system.adapter.wled.0 started with pid 18988
host.io-broker | 2021-09-13 21:26:30.474 | info | stopInstance system.adapter.wled.0 killing pid 18976
host.io-broker | 2021-09-13 21:26:29.471 | info | stopInstance system.adapter.wled.0 send kill signal
host.io-broker | 2021-09-13 21:26:29.428 | info | stopInstance system.adapter.wled.0 (force=false, process=true)
wled.0 | 2021-09-13 21:25:43.144 | error | Cannot read property 'error' of undefined
wled.0 | 2021-09-13 21:25:43.143 | error | TypeError: Cannot read property 'error' of undefined at Wled.onUnload (/opt/iobroker/node_modules/iobroker.wled/main.js:130:13) at Wled.emit (events.js:314:20) at process.stop (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8747:22) at Object.onceWrapper (events.js:421:26) at process.emit (events.js:314:20) at process.exit (internal/process/per_thread.js:168:15) at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:352:25) at processTicksAndRejections (internal/process/task_queues.js:97:5)
wled.0 | 2021-09-13 21:25:43.142 | error | unhandled promise rejection: Cannot read property 'error' of undefined
wled.0 | 2021-09-13 21:25:43.141 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
wled.0 | 2021-09-13 21:25:42.627 | warn | Terminated (ADAPTER_ALREADY_RUNNING): Without reason
wled.0 | 2021-09-13 21:25:42.627 | debug | Plugin sentry destroyed
wled.0 | 2021-09-13 21:25:42.624 | error | wled.0 already running
wled.0 | 2021-09-13 21:25:42.621 | debug | statesDB connected
wled.0 | 2021-09-13 21:25:42.620 | debug | States connected to redis: 127.0.0.1:9000
wled.0 | 2021-09-13 21:25:42.612 | debug | States create User PubSub Client
wled.0 | 2021-09-13 21:25:42.612 | debug | States create System PubSub Client
wled.0 | 2021-09-13 21:25:42.605 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
wled.0 | 2021-09-13 21:25:42.604 | debug | objectDB connected
wled.0 | 2021-09-13 21:25:42.599 | debug | Objects connected to redis: 127.0.0.1:9001
wled.0 | 2021-09-13 21:25:42.582 | debug | Objects client initialize lua scripts
wled.0 | 2021-09-13 21:25:42.581 | debug | Objects create User PubSub Client
wled.0 | 2021-09-13 21:25:42.580 | debug | Objects create System PubSub Client
wled.0 | 2021-09-13 21:25:42.579 | debug | Objects client ready ... initialize now
wled.0 | 2021-09-13 21:25:42.554 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
host.io-broker | 2021-09-13 21:25:41.936 | info | instance system.adapter.wled.0 started with pid 18976
host.io-broker | 2021-09-13 21:25:39.866 | info | stopInstance system.adapter.wled.0 killing pid 18965
host.io-broker | 2021-09-13 21:25:38.864 | info | stopInstance system.adapter.wled.0 send kill signal
host.io-broker | 2021-09-13 21:25:38.855 | info | stopInstance system.adapter.wled.0 (force=false, process=true)
wled.0 | 2021-09-13 21:25:32.475 | error | Cannot read property 'error' of undefined
wled.0 | 2021-09-13 21:25:32.475 | error | TypeError: Cannot read property 'error' of undefined at Wled.onUnload (/opt/iobroker/node_modules/iobroker.wled/main.js:130:13) at Wled.emit (events.js:314:20) at process.stop (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8747:22) at Object.onceWrapper (events.js:421:26) at process.emit (events.js:314:20) at process.exit (internal/process/per_thread.js:168:15) at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:352:25) at processTicksAndRejections (internal/process/task_queues.js:97:5)
wled.0 | 2021-09-13 21:25:32.473 | error | unhandled promise rejection: Cannot read property 'error' of undefined
wled.0 | 2021-09-13 21:25:32.473 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
wled.0 | 2021-09-13 21:25:31.960 | warn | Terminated (ADAPTER_ALREADY_RUNNING): Without reason
wled.0 | 2021-09-13 21:25:31.959 | debug | Plugin sentry destroyed
wled.0 | 2021-09-13 21:25:31.957 | error | wled.0 already running
wled.0 | 2021-09-13 21:25:31.954 | debug | statesDB connected
wled.0 | 2021-09-13 21:25:31.953 | debug | States connected to redis: 127.0.0.1:9000
wled.0 | 2021-09-13 21:25:31.946 | debug | States create User PubSub Client
wled.0 | 2021-09-13 21:25:31.946 | debug | States create System PubSub Client
wled.0 | 2021-09-13 21:25:31.940 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
wled.0 | 2021-09-13 21:25:31.938 | debug | objectDB connected
wled.0 | 2021-09-13 21:25:31.934 | debug | Objects connected to redis: 127.0.0.1:9001
wled.0 | 2021-09-13 21:25:31.922 | debug | Objects client initialize lua scripts
wled.0 | 2021-09-13 21:25:31.921 | debug | Objects create User PubSub Client
wled.0 | 2021-09-13 21:25:31.915 | debug | Objects create System PubSub Client
wled.0 | 2021-09-13 21:25:31.913 | debug | Objects client ready ... initialize now
wled.0 | 2021-09-13 21:25:31.885 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
host.io-broker | 2021-09-13 21:25:31.338 | info | instance system.adapter.wled.0 started with pid 18965
host.io-broker | 2021-09-13 21:25:29.263 | info | stopInstance system.adapter.wled.0 killing pid 18334
host.io-broker | 2021-09-13 21:25:28.260 | info | stopInstance system.adapter.wled.0 send kill signal
host.io-broker | 2021-09-13 21:25:28.220 | info | stopInstance system.adapter.wled.0 (force=false, process=true)


</body>
</html>`

Both WLED controllers are online and can be controlled via the browser and the app, but I cannot get a connection via IO-Broker:

![WLED Adapter Einstellungen](https://user-images.githubusercontent.com/69077006/133146167-5ca4cc20-beab-404a-a603-0fafcded5986.jpg)

![WLED 1](https://user-images.githubusercontent.com/69077006/133146181-e1477bf0-bd74-4139-a117-d63fe7d3c760.jpg)

![WLED 1 - Info](https://user-images.githubusercontent.com/69077006/133146199-fdd07238-af14-43a7-8277-ba26475d77e8.jpg)

![WLED 2](https://user-images.githubusercontent.com/69077006/133146226-87806c7b-93bb-488d-84d4-4602f73f9b6a.jpg)

![WLED 2 - Info](https://user-images.githubusercontent.com/69077006/133146240-e1c839a8-e275-47f8-b42f-7b5b8965ee97.jpg)

**Comment by FreunderNacht** [comment]
In the meantime I have it online again, since I now have access to my PC, I have restarted the entire Proxmox VM with IO Broker, and now everything seems to be working again:

![WLED Apapter Einstellungen](https://user-images.githubusercontent.com/69077006/133147366-346e352b-b199-4d37-9ba0-934c61941d64.jpg)

**Comment by DutchmanNL** [comment]
Thank you the logs absolutely help! It looks like the Ada is already running, so the error is just a Symptom caused by the already running process

Did you already try to reboot your system and check what happens then?

**Comment by FreunderNacht** [comment]
Restarting the adapter did not bring any success, only restarting the entire VM brought the WLEDs back online.

**Comment by FreunderNacht** [comment]
Thank you very much for the quick help.

**Comment by DutchmanNL** [comment]
> Restarting the adapter did not bring any success, only restarting the entire VM brought the WLEDs back online.

Great you solved it, look like during the adapter the previous version was not stopped correctly (somehow 🤷‍♂️) so rebooting the main is or ioBroker is the only solution
