### ISSUE TITLE
Segmentation Color HEX missing white channel

### ISSUE THREAD

**Issue by zakaszewski** [DrozmotiX/ioBroker.wled#305]
**Issue description:**

HEX color objects in segmentation (1.x) are missing the white channel, i.e. have format "#000000"-"#ffffff", whereas they SHOULD have the format "#00000000"-"#ffffffff"(if stripe has white channel, wled.0.[device-ID]._info.leds.rgbw==TRUE). This is not the case with the RGB array string objects (2.x), there the white channel is present and configurable ("[0,0,0,0]"-"[255,255,255,255]").

1.) HEX color objects
1.1) wled.0.[device-ID].seg.[segment-ID].col.0_HEX
1.2) wled.0.[device-ID].seg.[segment-ID].col.1_HEX
1.3) wled.0.[device-ID].seg.[segment-ID].col.2_HEX
2.) RGB array string objects
2.1) wled.0.[device-ID].seg.[segment-ID].col.0
2.2) wled.0.[device-ID].seg.[segment-ID].col.1
2.3) wled.0.[device-ID].seg.[segment-ID].col.2

---
**Steps to reproduce the behavior:**

3.1) Go to either WLED HEX color object in iobroker (stripe must be configured as RGBW)
3.2) Check object value
3.3) --> Only RGB value (SIX digits) is present, e.g. "#123456"
3.4) Try to enter (EIGHT digit) RGBW object value, e.g. "#12345678"
3.5) --> White channel is ignored

**Expected behavior**  

(3.3) --> Value should have EIGHT digits
(3.5) --> White channel should be accepted

---
**Screenshots & Logfiles**

n/a

---
**Versions:**

 - Adapter version "iobroker admin": v5.1.25
 - Adapter version "wled": v0.6.3
 - JS-Controller version: 3.3.18
 - Node version: v12.22.7
 - Operating system: Raspbian GNU/Linux 11 (bullseye) [on Raspberry 4, 4GB]

---
**Additional context**

n/a

**Comment by DutchmanNL** [comment]
Fixed in 0.6.8 thank you @trovanaffm please test from git, if successful I will release new 

please close or update this issue of testing is OK or you see any issues. Thank you !

**Comment by DutchmanNL** [comment]
released in v0.7.0
