### ISSUE TITLE
Segmentation Color RGB drops red channel before sending

### ISSUE THREAD

**Issue by zakaszewski** [DrozmotiX/ioBroker.wled#306]
**Issue description:**  
(When stripe has white channel configured --> wled.0.[device-ID]._info.leds.rgbw==TRUE,) Entering red channel value via HEX color objects (1.x) is possible, while red value entered via RGB array string objects (2.x) is dropped before sending to WLED device.

1.) HEX color objects
1.1) wled.0.[device-ID].seg.[segment-ID].col.0_HEX
1.2) wled.0.[device-ID].seg.[segment-ID].col.1_HEX
1.3) wled.0.[device-ID].seg.[segment-ID].col.2_HEX
2.) RGB array string objects
2.1) wled.0.[device-ID].seg.[segment-ID].col.0
2.2) wled.0.[device-ID].seg.[segment-ID].col.1
2.3) wled.0.[device-ID].seg.[segment-ID].col.2

---
**Steps to reproduce the behavior:**
3.1) Set logging for WLED adapter to DEBUG
3.2) Go to either WLED RGB array string object in iobroker objects (stripe must be configured as RGBW)
3.3) Enter any RGBW array string containing value for red, e.g. "[**128**,127,126,125]"
3.4) Check iobroker log, filter for "Sending state change by websocket"
3.5) --> Debug log output is "Sending state change by websocket {"seg":{"id":0,"col":[[**null**,127,126,125],[0,0,0,0],[0,0,0,0]]}}"
3.6) Go to either WLED HEX color object in iobroker objects (white channel not present, see #305)
3.7) Enter any RGB color containing value for red, e.g. "**ff**1122"
3.8) Check iobroker log, filter for "Sending state change by websocket"
3.9) --> Debug log output is "Sending state change by websocket {"seg":{"id":0,"col":[[**255**,17,34],[0,0,0],[0,0,0]]}}"

---
**Expected behavior**  
(3.5) should state "Sending state change by websocket {"seg":{"id":0,"col":[[**128**,127,126,125],[0,0,0,0],[0,0,0,0]]}}"

---
**Screenshots & Logfiles**  
n/a

---
**Versions:**  
 - Adapter version "iobroker admin": v5.1.25
 - Adapter version "wled": v0.6.3
 - JS-Controller version: 3.3.18
 - Node version: v12.22.7
 - Operating system: Raspbian GNU/Linux 11 (bullseye) [on Raspberry 4, 4GB]
---
**Additional context**  
n/a

**Comment by DutchmanNL** [comment]
Fixed in 0.6.8 thank you @trovanaffm please test from git, if successful I will release new 

please close or update this issue of testing is OK or you see any issues. Thank you !

**Comment by DutchmanNL** [comment]
released in v0.7.0
