### ISSUE TITLE
Devices reported as offline after update to v0.13.0-b5

### ISSUE THREAD

**Issue by kopierschnitte** [DrozmotiX/ioBroker.wled#307]
**Describe the bug**  
After I've updated my ESP32/ESP8266 controllers to WLED v0.13.0-b5, the WLED adapter keeps telling me that the controllers are offline (wled.0.XXX._info._online == false) and the icon next to each controller is red.
Everything else works as expected. Even signal and rssi is updated frequently.

**To Reproduce**  
1. Update WLED controller to v0.13.0-b5
2. Check connection state in the adapter

**Expected behavior**  
Adapter should show the correct connection status.

**Versions:**  
 - Adapter version: 0.6.3
 - JS-Controller version: 3.3.18
 - Node version: 14.18.1
 - Operating system: Ubuntu

**Comment by itwegner72** [comment]
I have the same Issue. It´s not working since Version higher than Wled Version 0.12.0 .

**Comment by schluff81** [comment]
I have the same issue since 0.12.0

Wled android app is working as expected while iobroker wled Adapter  has no connection to wled. New adding of Devices helps but only for a limited time

**Comment by mamsoft** [comment]
Hello, I have the same issue since 0.12.0

I used 10 of weld Modules and 4 are connected and the other 6 are disconnected

**Comment by Reddy-X** [comment]
Hi there, 

I have the same issue since 0.12.0 in combination with the iobroker adapter 0.6.3

Wled android app is working fine.

Aboud a week iobroker wled adapter has no connection to wled. 

Deleting folders of wled and adding the devices again helps, but only for a limited time.

I love wled, and would be happy if it works again

**Comment by kopierschnitte** [comment]
Problem remains on v0.13.0-**b6**

**Comment by rmp63526** [comment]
Same issue here as well! v0.13.0-b6

**Comment by S3DD3S** [comment]
Same here. All controllers are offline (red connection status) and i cant turn it on or off. Restart helps but only for a limited time. Any solutions?

**Comment by pforrmi** [comment]
Same issue here v0.13.0-b6

**Comment by pforrmi** [comment]
@S3DD3S 
Use v0.12.0 for now. Looks like that with that version is no problem with the connection.

**Comment by Reddy-X** [comment]
I tested it with Version 12.0. For me it reproduced the same problems. A similar Problem has been discussed several times in older closed topics.

**Comment by Mekki1402** [comment]
I have the same problem. After a certain period the adapter losts the connection to the wled controller(red connection status).
The control from the wled web interface works fine during this time.
Any solutions so far?

**Comment by m0uh85** [comment]
Adapter v0.6.3
Same here: 
WLED 0.12.0 with works fine
WLED 0.13.1 (and all tested betas) lose connection after a while

**Comment by capitaenz** [comment]
Same here

**Comment by DutchmanNL** [comment]
solved [v0.6.4](https://github.com/DrozmotiX/ioBroker.wled/releases/tag/v0.6.4)
