### ISSUE TITLE
WLED Adapter Multiple Instances Issue

### ISSUE THREAD

**Issue by Percy2Live** [DrozmotiX/ioBroker.wled#315]
From time to time the WLED adapter stops working. It seems this oftenly happens when the ioBroker system is restartet or the WLED controller. The adapter is not working even after a restart. 

Via commandline you can see that multiple processes are running - after all but one are terminated, the adapter is working again.
The log file indicates this multiple instance issue:
![image](https://user-images.githubusercontent.com/63621052/145573438-90408d75-75c7-4a84-a8f7-29103a54750a.png)

More information can be found in this thread:

https://forum.iobroker.net/topic/49091/wled-adapter-nach-neustart-keine-verbindungen-mehr-m%C3%B6glich 

**Versions:**  
 - Adapter version: 0.6.3
 - JS-Controller version: 3.3.18 
 - Node version: 14.18.1 
 - Operating system: Docker Container

**Comment by DutchmanNL** [comment]
this should not happen anymore in 0.6.5
