### ISSUE TITLE
Latest version flooding the logs

### ISSUE THREAD

**Issue by zeromancer1972** [DrozmotiX/ioBroker.wled#409]
Is it intentional that the adapter floods the logs with INFO about WLED devices being connected? It's annoying, please add a log level or remove the INFO logging on that esp. if the states/connectivity doesn't change at all.

**Comment by DutchmanNL** [comment]
> Is it intentional that the adapter floods the logs with INFO about WLED devices being connected? It's annoying, please add a log level or remove the INFO logging on that esp. if the states/connectivity doesn't change at all.

Sharing the log and Version you use would help… no ist not normal

**Comment by DutchmanNL** [comment]
@zeromancer1972 can you share the logs please?

**Comment by MC-1984** [comment]
I have a related issue. I cut the power to all 10 of my ESPs and LED stripes when I don't need them. That also floods the log:

As you can see I also have the info about the reconnection in the log. Maybe it is possible to get both log entries only in debug or silly setting?

`
wled.0 | 2022-07-14 23:02:51.181 | warn | Device 192.168.50.210 offline, will try to reconnect
-- | -- | -- | --
wled.0 | 2022-07-14 23:02:38.679 | info | WLED-004 connected
wled.0 | 2022-07-14 23:02:37.050 | info | Initialising : " WLED-004" on IP : 192.168.50.204
wled.0 | 2022-07-14 23:02:15.773 | info | WLED-004 connected
wled.0 | 2022-07-14 23:02:14.820 | info | Initialising : " WLED-004" on IP : 192.168.50.204
wled.0 | 2022-07-14 23:01:47.695 | info | WLED-010 connected
wled.0 | 2022-07-14 23:01:46.367 | info | Initialising : " WLED-010" on IP : 192.168.50.210
wled.0 | 2022-07-14 23:01:38.613 | error | Sending command to WLED device + http://192.168.50.210/json failed with error Error: connect EHOSTUNREACH 192.168.50.210:80
wled.0 | 2022-07-14 23:01:38.611 | error | Sending command to WLED device + http://192.168.50.210/json failed with error Error: connect EHOSTUNREACH 192.168.50.210:80
wled.0 | 2022-07-14 22:59:52.345 | error | Sending command to WLED device + http://192.168.50.210/json failed with error Error: connect EHOSTUNREACH 192.168.50.210:80
wled.0 | 2022-07-14 22:59:52.339 | error | Sending command to WLED device + http://192.168.50.210/json failed with error Error: connect EHOSTUNREACH 192.168.50.210:80
wled.0 | 2022-07-14 22:59:22.487 | error | Sending command to WLED device + http://192.168.50.210/json failed with error Error: connect EHOSTUNREACH 192.168.50.210:80
wled.0 | 2022-07-14 22:59:22.482 | error | Sending command to WLED device + http://192.168.50.210/json failed with error Error: connect EHOSTUNREACH 192.168.50.210:80
wled.0 | 2022-07-14 22:59:05.842 | error | Sending command to WLED device + http://192.168.50.210/json failed with error Error: connect EHOSTUNREACH 192.168.50.210:80
wled.0 | 2022-07-14 22:58:57.362 | error | Sending command to WLED device + http://192.168.50.210/json failed with error Error: connect EHOSTUNREACH 192.168.50.210:80
wled.0 | 2022-07-14 22:58:51.123 | error | Sending command to WLED device + http://192.168.50.210/json failed with error Error: connect EHOSTUNREACH 192.168.50.210:80
wled.0 | 2022-07-14 22:58:51.122 | error | Sending command to WLED device + http://192.168.50.210/json failed with error Error: connect EHOSTUNREACH 192.168.50.210:80
wled.0 | 2022-07-14 22:58:43.445 | error | Sending command to WLED device + http://192.168.50.210/json failed with error Error: connect EHOSTUNREACH 192.168.50.210:80
wled.0 | 2022-07-14 22:58:43.444 | error | Sending command to WLED device + http://192.168.50.210/json failed with error Error: connect EHOSTUNREACH 192.168.50.210:80
wled.0 | 2022-07-14 22:58:43.443 | error | Sending command to WLED device + http://192.168.50.210/json failed with error Error: connect EHOSTUNREACH 192.168.50.210:80
wled.0 | 2022-07-14 22:58:43.442 | error | Sending command to WLED device + http://192.168.50.210/json failed with error Error: connect EHOSTUNREACH 192.168.50.210:80
wled.0 | 2022-07-14 22:58:33.334 | error | Sending command to WLED device + http://192.168.50.202/json failed with error Error: connect ETIMEDOUT 192.168.50.202:80
wled.0 | 2022-07-14 22:58:33.333 | error | Sending command to WLED device + http://192.168.50.202/json failed with error Error: connect ETIMEDOUT 192.168.50.202:80
wled.0 | 2022-07-14 22:58:33.332 | error | Sending command to WLED device + http://192.168.50.202/json failed with error Error: connect ETIMEDOUT 192.168.50.202:80
wled.0 | 2022-07-14 22:58:33.330 | error | Sending command to WLED device + http://192.168.50.202/json failed with error Error: connect ETIMEDOUT 192.168.50.202:80
wled.0 | 2022-07-14 22:57:54.161 | error | Sending command to WLED device + http://192.168.50.210/json failed with error Error: connect EHOSTUNREACH 192.168.50.210:80
`

**Comment by DutchmanNL** [comment]
> I have a related issue. I cut the power to all 10 of my ESPs and LED stripes when I don't need them. That also floods the log:

hmm that's expected behavior, you cut the power off so the device is not reachable but stilll send commands to the related Datapoints sos I assume a script or scene is causing that ?
Changing this message to debug or silly is unwanted, as people would miss the message in "normal situation".

So question is, why do you switch device if not needed ;)

**Comment by MC-1984** [comment]
I don't know why the device was not reachable. But you are correct in assuming that I use scripts that control the LEDs.

Thanks for the explanation that it is expected behaviour in normal situations. Makes total sense not to change it.

**Comment by DutchmanNL** [comment]
> I don't know why the device was not reachable. But you are correct in assuming that I use scripts that control the LEDs.
> 
> Thanks for the explanation that it is expected behaviour in normal situations. Makes total sense not to change it.

as suggestion, if u use a script... you can always add a if clausure to check the _online datapoint in the info channel.
If that value is false, it makes no sense to send values.

If you do, the adapter throws the error to inform user the value cannot be set. This helps in error analyzing imagine you make a script or change the DP but nothing happens.... now at least the log guide you into an direction :)

**Comment by MC-1984** [comment]
@DutchmanNL Good idea, I will check the _online datapoint. Thanks!

**Comment by DutchmanNL** [comment]
as I see no response from @zeromancer1972 and the issue looks related to the message of unavailable devices (as explained) I close this issue for now.

If there are any additional questions or follow-up needed feel free to reopen

**Comment by zeromancer1972** [comment]
Sorry, totally lost track here since the plugin has other issues, I will report later.
Yes, I have the same logs as mentioned before.
