### ISSUE TITLE
_online DP as value not JSON

### ISSUE THREAD

**Issue by mcuiobroker** [DrozmotiX/ioBroker.wled#410]
_online DP ist JSON
```
{"val":false,"ack":true}
```

![image](https://user-images.githubusercontent.com/84818934/178127002-7200f9ef-fdfd-4d50-a40a-bd73fc4a5884.png)
Please make it as real boolean.
![image](https://user-images.githubusercontent.com/84818934/178127031-27abec45-e3d2-4fd6-b279-441e5030e101.png)

Thank you.

**Comment by DutchmanNL** [comment]
hmm strange, I don't have that and the code write a clean boolean.... which version are you using (WLED and Admin) ?
<img width="1465" alt="Schermafbeelding 2022-07-10 om 08 56 31" src="https://user-images.githubusercontent.com/7318445/178134590-fb2a42b5-2b32-4a08-ac98-1f8faf86423e.png">

**Comment by mcuiobroker** [comment]
admin 5.3.2
WLED 0.6.7

**Comment by DutchmanNL** [comment]
Ich kan es nicht reproduzieren 🤷‍♂️
Mach mal bitte ein scripties lese damit den dp aus, möchte wissen ob es ein Anzeige Fehler des Admin ist.

Also zb ein blockly mit debug Baustein und dan weet von diesen datenpunkt

**Comment by mcuiobroker** [comment]
Hab schon die Objekte gelöscht und neugestartet. Jetzt passt es. Komisch. Aber ok. Danke.
![image](https://user-images.githubusercontent.com/84818934/178134870-f14213ad-3e48-4d09-9aa7-cf0a5282a3f0.png)
