### ISSUE TITLE
Get the roles right...

### ISSUE THREAD

**Issue by Garfonso** [DrozmotiX/ioBroker.wled#428]
**Describe the bug**  
WLED Adapter uses some self defined roles and uses some other roles wrongly. For reference of roles, see here: https://www.iobroker.net/#en/documentation/dev/stateroles.md

Some roles that definitively should be changed / corrected:
1. `bri` should have role `level.brightness`. **value** is **Number, read only**. But the state has write flag set to true. So my assumption is that the state is used to control brightness and not only display values reported by the device (which the value role suggests). Change this, the lamp will already be detected as dimmable.
2. `on` state could also be `switch.light` to make detection more robust.
3. Not sure if you use `level.color.rgb` right. Documentation says, that it is a hex value anyway. There is no `level.color.hex` role defined in ioBroker (so use is not really allowed). If the states with `level.color.rgb` accept an array instead of hex string, then there is no clear role for that. We should define a new one, then, and change roles accordingly.
4. `_online`  state is currently not well-supported in ioBroker / type-detector. So it might be an enhancement to replace it / add an offline state with `indicator.maintenance.unreach`.

Not sure how color is controlled, yet... 

Also see issue reported in lovelace https://github.com/ioBroker/ioBroker.lovelace/issues/380

**Comment by DutchmanNL** [comment]
thank you PR accepted

**Comment by trovanaffm** [comment]
I think this issue is solved, by @Garfonso PR.

**Comment by DutchmanNL** [comment]
released in v0.7.0
