### ISSUE TITLE
WLED adapter stopped working with Javascript/Blockly engine

### ISSUE THREAD

**Issue by zeromancer1972** [DrozmotiX/ioBroker.wled#434]
**Describe the bug**  
All my scripts (blockly) stopped working properly, I cannot control WLED's "ps" or "on" properties repliably.
I can manually in the objects, but not script-controlled.
They used to work before and stopped a few days ago. Not sure if JS adapter is to blame or this plugin.

To reproduce: create a simple script that just controls the "ps" property - nothing will happen.
To be clear: sometimes it works, but in 80% of switch events it does not.

I just created a script that sets "ps" to a "on" preset when I click a button and to a "ps" that switched the WLED off. Debugger shows the button state perfectly but WLED does not react to that accordingly. Is there a certain amount of "waiting" time between switch events I have to obey?

**Versions:**  
 - Adapter version: v0.6.7
 - JS-Controller version: v6.0.0
 - Node version: v16.14.0 
 - Operating system: Linux Ubuntu

**Additional context**

**Comment by zeromancer1972** [comment]
This is the little test script
```javascript
on({id: "zigbee.0.5c0272fffe58f743.state"/*Switch event*/, change: "any"}, async function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  if (getState("zigbee.0.5c0272fffe58f743.state").val) {
    console.log('ON');
    setState("wled.0.2c3ae845304c.ps"/*ID of currently set preset*/, 80);
  } else {
    console.log('OFF');
    setState("wled.0.2c3ae845304c.ps"/*ID of currently set preset*/, 100);
  }
});
```

The logs show nothing except my own console messages.

**Comment by Apollon77** [comment]
why you use getState of the same state as the trigger? This can have side effects ... always use the "value" variable!

**Comment by zeromancer1972** [comment]
Adapter is v6.0.0 and I have no issues since I get the correct log messages. If-else is working properly, but the setState for WLED does not.

**Comment by Apollon77** [comment]
Ok, then ...but still strange that it stopped working without any update ... tried restarting host/iobroker?

**Comment by zeromancer1972** [comment]
I tried the usual stuff already. Rebooting, restarting, restarting the adapter, restarting the ESP. I found a workaround now using the HTTP API of WLED directly with NodeRed

**Comment by Apollon77** [comment]
maybe was there a wled firmware update or such?

**Comment by zeromancer1972** [comment]
WLED firmware update was done moths ago, it stopped working 2 days ago

**Comment by Apollon77** [comment]
Tried to poer off(on the devices? Sorry for asking such dump questions but why an adapter should stop wirking when nothing was changed?

**Comment by zeromancer1972** [comment]
Tried everything. I have no explanation for it.

**Comment by zeromancer1972** [comment]
I just found out that using scenes still works, so it's currently "only" Javascript/Blockly that is not working

**Comment by Apollon77** [comment]
Which makes it ebvene more intersesting ... So via Admin also works? maybe turned on simulation mode of the script in Admin or such?

**Comment by zeromancer1972** [comment]
Never seen "simulation mode" so I don't think I accidentally enabled that. Setting the ps property via the object/datapoint works, too

**Comment by DutchmanNL** [comment]
I think this should be further analyses or researched at the JavaScript adapter, as you are able to control wled by the states in admin the adapter is working question is way your script is not working anymore.

That can have several reasons, like another script causing the JavaScript adapter to crash

Wled firmware and adapter looks fine, otherwise you could not control it al all

**Comment by DutchmanNL** [comment]
as we have no follow up here an I still think its related to javascript engine, I will close for now :)
