### ISSUE TITLE
Connection Status falsch - True obwohl nicht angeschlossen

### ISSUE THREAD

**Issue by JBSullivan** [DrozmotiX/ioBroker.wled#438]
Ich verwende derzeit zwei Wled Controller mit dem Wled Adapter (V0.6.7). Einer ist aktiv im Netzwerk, der zweite wird nur temporär eingesteckt und ist aktuell NICHT angeschlossen. Trotzdem wird der Connection Status und der RSSI Status von diesem Wled Gerät als True, bzw. mit 88% angezeigt und in den Objekten beim aktualisieren "grün" hervorgehoben. Wie gesagt, angeschlossen ist dieses Gerät nicht und es gibt im Netzwerk auch kein anderes aktives Gerät, welches zufällig die gleiche IP Adresse benutzt. 

![image](https://user-images.githubusercontent.com/44617472/191442961-4bedb323-8a92-4299-b116-0e8761d7646f.png)

**Comment by JBSullivan** [comment]
Adapter habe ich oben geschrieben - 06.7. Firmware von beiden Controllern ist 0.12.0

**Comment by trovanaffm** [comment]
@JBSullivan der connection State zeigt dir ob die WLED Instanz innerhalb des IOBrokers erreichbar ist. 
Dies hat nichts mit den Controllern zu tun. 
Um zu überprüfen ob ein WLED Controller erreichbar ist schau dir mal den Datenpunkt an:
WLED-->0-->Nummer deines Controllers --> _info -->_online
Dort wird der Online Zustands bzg. deines Controllers aufgeführt. 
Dies ist natürlich abhängig davon, in welchem Zeitrhytmus deine Controller abgefragt werden.

**Comment by DutchmanNL** [comment]
Wegen in Aktivität geschlossen, sollte weiterhin bedarf seine gerne neu öffnen :)
