### ISSUE TITLE
WLED 0.14.0-b1:set preset wird beim Einschalten nicht mehr übergeben

### ISSUE THREAD

**Issue by guergen1** [DrozmotiX/ioBroker.wled#478]
Beim Ausschalten wird der Wert vom DP "ps" auf "-1" gesetzt und beim Einschalten nicht wieder auf die Preset-Nummer.
Wenn ich zurück auf die WLED 0.13.3 gehe, wird der Wert wieder übertragen.

WLed-Adapter: 0.6.7
WLED-Bin: 0.14.0-b1
js-controller: 4.0.24
Node.js: 16.19.0
NPM: 8.19.3

**Comment by DutchmanNL** [comment]
Das liegt an wled, wen die Werte so über die api kommen.

Da es mit anderer Firmware Version geht tippe ich mal auf ein Problem (oder gewollte Änderung) bei wled

**Comment by guergen1** [comment]
Falls es eine gewollte Veränderung ist, ist das hier ja richtig...
