### ISSUE TITLE
Read ESP Pins 

### ISSUE THREAD

**Issue by maxpd1** [DrozmotiX/ioBroker.wled#485]
**Describe wanted Enhancement !**  
I want to read out the other PINs on the ESP288 (Wemos D1 Mini). For example: connected with LED Stripe there is at the same time an HC-SR501 motion sensor. Via iobroker I can detect the motion when the pin shows "true" state and control single segments.

**Why should we put effort in it ?**  
You don't need a separate ESP288 for motion sensor anymore.

**Comment by DutchmanNL** [comment]
I cannot do that please raised your enhancement at the WLED Projekt.

If they integrate it and expose by API this adapter can manage the values and states

**Comment by DutchmanNL** [comment]
i will close for now, please feel free to reopen if required

**Comment by maxpd1** [comment]
The point is that wled won't implement a pin readout as they offer mqtt interface for that. Unfortunately I don't get a successful Mqtt connection with any device. No matter if wled or not.

An option would be that this adapter adds mqtt attribute readout. Otherwise I am still trying to find the solution for my mqtt problem.

**Comment by DutchmanNL** [comment]
> The point is that wled won't implement a pin readout as they offer mqtt interface for that. Unfortunately I don't get a successful Mqtt connection with any device. No matter if wled or not.
> 

do you have a reference of that? It makes no sense to provide an api and mqtt but not implement data on both

**Comment by maxpd1** [comment]
That's how I understood this comment https://github.com/Aircoookie/WLED/issues/3039#issuecomment-1387059079

**Comment by DutchmanNL** [comment]
> That's how I understood this comment [Aircoookie/WLED#3039 (comment)](https://github.com/Aircoookie/WLED/issues/3039#issuecomment-1387059079)

I legt a comment there for airkookie

**Comment by DutchmanNL** [comment]
@maxpd1 response in WLED issue:

However, I don't think that it is a feature that is required in most installs and worth the JSON overhead by default. WLED can in principle offer the flexibility of ESPHome or the likes, but that is what usermods are for.
So I'd propose adding the functionality of reading and outputting GPIO values via /json/info as a usermod.

implementing it as a user mod should work in current version of this Adapter

**Comment by maxpd1** [comment]
Yes, read it. Thank you.
I think most of the WLED users aren't able to write a usermod.
But I'll check further here: https://wled.discourse.group/c/usermods/11

**Comment by DutchmanNL** [comment]
> Yes, read it. Thank you.
> I think most of the WLED users aren't able to write a usermod.
> But I'll check further here: https://wled.discourse.group/c/usermods/11

If you succeed, I know for sure others would be very happy if you share how 😅
