### ISSUE TITLE
Datapoint cct has no effect  

### ISSUE THREAD

**Issue by niiccooo1** [DrozmotiX/ioBroker.wled#569]
**Describe the bug**  
The datapoint CCT has no effect on the light 

**To Reproduce**  
1. Click on cct
2. Add a value between 0 and 255 
3. Value change doesn't effect the light

**Expected behavior**  
Change the colour temperature between warm and cold white

**Versions:**  
 - Adapter version: 0.7.0
 - JS-Controller version: 4.0.24
 - Node version: 18.17.1
 - Operating system: Linux Mint - Docker

**

**Comment by HaggardFFM** [comment]
@niiccooo1 
Which type of LED Stripe are you using. 
In the description of WLED there is only CCT available for PVM Strips not for digital LED Strip. 
Have a look at the documentation: [https://kno.wled.ge/features/cct/](https://kno.wled.ge/features/cct/)

**Comment by niiccooo1** [comment]
I'm using WS2815 addressable LED-Stripes.
I guess these kind is not supported, right?

I thought because in the WLED App I could change the colour temperature by a slider 

![Screenshot_20230825-213538](https://github.com/DrozmotiX/ioBroker.wled/assets/109716928/b63b4cae-b613-4ac9-b1ca-4a3dcba9655a)

Maybe a feature request to change this value over a DP.

**Comment by HaggardFFM** [comment]
@niiccooo1 
As descripted in the documentation this slider changes the color information. 
Have a look in your IOBroker under subfolder col. 
When you move the CCT slider, a new color Code (HEX and DEC) will be written at your datapoint seg.0.col.0 and seg.0.col.0_HEX. 
So this slider change the color of the led. 
Actually there is no LED Stripe on the market which works on digital base and have RGBCWWW. This are all analouge PWM Stripes. 
I use SK6812 stripes which comes with RGB W (in my Case WW). With them you get an additional slider only for the White LEDS.
![image](https://github.com/DrozmotiX/ioBroker.wled/assets/62116621/4db09095-982b-417e-8f6a-3dea701ca048)
