### ISSUE TITLE
State info.online wrong type

### ISSUE THREAD

**Issue by ToTXR4Y** [DrozmotiX/ioBroker.wled#611]
State value to set for "wled.0.ecfabc6316aa._info._online" has to be type "boolean" but received type "string" .

Passiert wenn das Gerät sich vom WLAN abmeldet.

**Comment by DutchmanNL** [comment]
> State value to set for "wled.0.ecfabc6316aa._info._online" has to be type "boolean" but received type "string" .
> 
> Passiert wenn das Gerät sich vom WLAN abmeldet.

hmm ich kan das so nicht reproduzieren, mir ist dabei aber aufgefallen das der Online status garnicht mehr auch falsch geht wen das gerät wifi verliert ist das bei dir auch so ?
