### ISSUE TITLE
HEX values not updating with wled 0.14.2 or higher firmware

### ISSUE THREAD

**Issue by baetzmr** [DrozmotiX/ioBroker.wled#676]
**Describe the bug**  
Updated my ESP32 devices to wled 0.14.2. Since that my HEX values in seg/0/col not getting updated when chaning the color.

**To Reproduce**  
Update wled devices to 0.14.2 or higher (0.15.0-b1)

**Expected behavior**  
with wled 0.14.1 everything is working fine.

**Screenshots & Logfiles**  
![image](https://github.com/DrozmotiX/ioBroker.wled/assets/81546284/a9b90fd9-4de6-48d1-95ae-14cf23ca4fba)

**Versions:**  
 - Adapter version: 0.7.2
 

**Additional context**  
downgraded all my devices back to wled 0.14.1 to get the HEX values updated when chaning the color.

**Comment by HaggardFFM** [comment]
@baetzmr 
I tested it today with WLED 0.14.3.
Everything works fine with it. 
Which version of the Adapter do you use ? 
![image](https://github.com/DrozmotiX/ioBroker.wled/assets/62116621/8c16a79b-9197-4229-899a-a2f4de77b298)
![image](https://github.com/DrozmotiX/ioBroker.wled/assets/62116621/c72bb1ba-380c-4237-a66e-8f25ee05cff5)
![image](https://github.com/DrozmotiX/ioBroker.wled/assets/62116621/c2f0224b-4842-4143-a639-79c904b20186)

**Comment by HaggardFFM** [comment]
@baetzmr 
Please close this issue if you haven't any other bugs with this issue. 
Solution was to delete the WLED once in the adapter and reassign it. 
Discussed in Discord WLED Server (#iobroker) 

Thanks
Harald
