### ISSUE TITLE
Scrolling text: <trail> value not available

### ISSUE THREAD

**Issue by Haifeif** [DrozmotiX/ioBroker.wled#688]
The <scrolling text> effect of WLED is used to display meta data of songs played. So far, so good. But the there is a <trail> value at the WLED web gui, that is always set to 128 at startup. It produces a kind of shadow to the scrolling text which makes it harder to read. Using the web gui to set it to 0 is possible and solves the problem of the text shadow. But I can't find the value at the iob-adapter. 

When I change it by the web-gui, the adapter shows it at <wled.0.083af2ad4c6c.seg.0.c1>. But <c1> is read only ...

If there is a parameter already, please let me know. If not, I would appreciate to have it at the adapter!

Keep up with the great work!

Rgds, Uwe

**Comment by HaggardFFM** [comment]
@Haifeif
I changed the C1 - C3 Values to writeable. 
If @DutchmanNL merge my pull request you will have the possibility to change this values. 

regards
Harald

**Comment by Haifeif** [comment]
Thanx, Harald!
Danke, Harald! 

Entschuldige meine Unkenntnis: Gibt es dann eine neue Version des Adapters? Oder kann ich irgendetwas "manuell" tun?

LG Uwe

**Comment by DutchmanNL** [comment]
> Hallo Uwe, 
> 
> da @DutchmanNL meinen Pull request noch nicht eingefügt hat, gibt es noch keine neue Version. 
> 
> Was du machen kannst (manuell) ist der Austausch oder die Bearbeitung der stateAttr.js Datei. 
> 
> ich hänge dir die neue Version hier an. 
> 
> [stateAttr.zip](https://github.com/DrozmotiX/ioBroker.wled/files/15285686/stateAttr.zip)
> 
> 
> 
> Diese Datei kopierst du dann in deinen IO Broker.  unter node_modules/iobroker.wled/lib und ersetzt die dort vorhandene Datei 
> 
> (Vorher eine Sicherungskopie anlegen) oder die originale einfach umbenennen. 
> 
> 
> 
> Anschliessend die Instanz neustarten, danach sollten die Werte c1 - c3 beschreibar sein. 
> 
> 
> 
> VG Harald
> 
> 
> 
> 

Ich kümmere mich diese Woche drum, danke für den PR

**Comment by HaggardFFM** [comment]
> > Hallo Uwe,
> > da @DutchmanNL meinen Pull request noch nicht eingefügt hat, gibt es noch keine neue Version.
> > Was du machen kannst (manuell) ist der Austausch oder die Bearbeitung der stateAttr.js Datei.
> > ich hänge dir die neue Version hier an.
> > [stateAttr.zip](https://github.com/DrozmotiX/ioBroker.wled/files/15285686/stateAttr.zip)
> > Diese Datei kopierst du dann in deinen IO Broker.  unter node_modules/iobroker.wled/lib und ersetzt die dort vorhandene Datei
> > (Vorher eine Sicherungskopie anlegen) oder die originale einfach umbenennen.
> > Anschliessend die Instanz neustarten, danach sollten die Werte c1 - c3 beschreibar sein.
> > VG Harald
> 
> Ich kümmere mich diese Woche drum, danke für den PR

Danke schön.

**Comment by DutchmanNL** [comment]
merge done, auch einige updates mit dependencies gemacht bitte die neue beta testen :)

**Comment by HaggardFFM** [comment]
@DutchmanNL looks good. 
Acutally there are no errors in the log.

**Comment by HaggardFFM** [comment]
@DutchmanNL 
No errors after 24 h in the new Beta. 
I think you can generate a new Release Version. 
best regards
Harald

**Comment by DutchmanNL** [comment]
> @DutchmanNL No errors after 24 h in the new Beta. I think you can generate a new Release Version. best regards Harald

perfect thanks, will check if there are some other small stuff which are worth to include and make a new release + publish request to stable this weekend
