### ISSUE TITLE
0.7.3beta error when device not available

### ISSUE THREAD

**Issue by liv-in-sky** [DrozmotiX/ioBroker.wled#698]
ich bekomme dauerhaft meldung über axios, wenn die devices nicht online sind (was beabsichtigt ist) - das log wird einfach überfüllt - bitte, wenn überhaupt, eine warnung daraus machen

![Image 035](https://github.com/DrozmotiX/ioBroker.wled/assets/18462890/385f306a-5ed4-4377-9c3b-3608becb8324)

**Comment by intruder7777** [comment]
Bei mir auch so. Bin deswegen wieder eine Version zurück

**Comment by haselchen** [comment]
> Bitte Version zurück bleiben in der Beta hat sich was älteres eingeschlichen werde ich so schnell wie möglich ausbügeln aber erstmal sohnemann sein Geburtstag organisieren 😅

Moin Moin....hast Du den Fix noch auf dem Schirm?
Sonst hat Dein Sohnemann bald wieder Geburtstag ;)

**Comment by DutchmanNL** [comment]
should be solved, please try latest version from git (0.7.3-beta.1)

**Comment by dolomiti70** [comment]
Nach dem Update auf 0.7.3 im stable-Zweig kommen Warnungen bei Geräten die offline sind. Das spammt mir den Log voll. Ich habe als Workaround die Geräte in den Objekten gelöscht, da es in den Instanzeinstellungen keinen Knopf zum löschen gibt. 
Die offline Geräte waren nur zum testen drin, sind also für mich aktuell kein Problem. Eine Dauerlösung ist das aber für mich nicht.

**Comment by DutchmanNL** [comment]
> Nach dem Update auf 0.7.3 im stable-Zweig kommen Warnungen bei Geräten die offline sind. Das spammt mir den Log voll. Ich habe als Workaround die Geräte in den Objekten gelöscht, da es in den Instanzeinstellungen keinen Knopf zum löschen gibt. Die offline Geräte waren nur zum testen drin, sind also für mich aktuell kein Problem. Eine Dauerlösung ist das aber für mich nicht.

Bitte in #786 weiter 👌
