### ISSUE TITLE
Spacing and grouping writable

### ISSUE THREAD

**Issue by xozy22** [DrozmotiX/ioBroker.wled#706]
Hey developers,
I saw in merge requests, that spacing is planned to be writable.
Do you also plan to make grouping accessible + writable?
When do you plan the next release?
Thanks in Advance!

**Comment by DutchmanNL** [comment]
@xozy22 thank you, if provided by API/websocket it should be straight forward to implement 

I'm an business travel until end of next week :/ 

Please do me a favour, send me a reminder next weekend, just need to flash an esp here and evaluate the api

**Comment by HaggardFFM** [comment]
Hi @DutchmanNL , 
I checked this, and the datapoints are still in the stateAttr.js but not marked as writeable. 
I can change this and post a pull request. 

But have you the issue #698 in the run. 
There was an error with axios by the last beta build. Please correct this before you generate a next beta. 

Greeting Haggard

**Comment by xozy22** [comment]
@HaggardFFM 
Sorry, did not saw your commit #707 
Thanks for your work so far!
Then @DutchmanNL, you should really only have #698 in mind.

BR

**Comment by HaggardFFM** [comment]
Hi @xozy22, 
these DATAPOINTS are integrated, so you see them in the Objecttree of WLED, but they was not writable. 
So I changed this, and send a pull request for integrate it to the main repo. 
After @DutchmanNL build a new Beta Version, you can install it in your IOBROKER and test it. 
But there was another problem with the last beta, so @DutchmanNL has to check it first, 
BR

**Comment by xozy22** [comment]
@HaggardFFM 
Just testet your implementation, but I will roll back to stable until @DutchmanNL fixed the other issue.
<img width="1393" alt="image" src="https://github.com/user-attachments/assets/accbf49a-0e1e-443e-94d5-68387e7e35dd">
<img width="1432" alt="image" src="https://github.com/user-attachments/assets/6ef11b3b-6864-48cb-b3cf-a05524d3040a">

Thank you all! Very appreciating!
BR

**Comment by DutchmanNL** [comment]
> Hi @xozy22, 
> 
> these DATAPOINTS are integrated, so you see them in the Objecttree of WLED, but they was not writable. 
> 
> So I changed this, and send a pull request for integrate it to the main repo. 
> 
> After @DutchmanNL build a new Beta Version, you can install it in your IOBROKER and test it. 
> 
> But there was another problem with the last beta, so @DutchmanNL has to check it first, 
> 
> BR
> 
> 
> 
> 

Thank you clarifying that Safes me quite some time understanding those relationships!

Will look into the mentioned connection issue und merge the changes

**Comment by DutchmanNL** [comment]
should be solved, please try latest version from git (0.7.3-beta.1)

**Comment by DutchmanNL** [comment]
any feedback ?

**Comment by xozy22** [comment]
Tested it - looks good so far.
Thank you.
